<?php

namespace MobileCart\FedexBundle\Api\RateV10\SimpleType;

/**
 *
 *
 */
class EdtTaxType extends SimpleTypeAbstract
{
    const ADDITIONAL_TAXES = 'ADDITIONAL_TAXES';

    const CONSULAR_INVOICE_FEE = 'CONSULAR_INVOICE_FEE';

    const CUSTOMS_SURCHARGES = 'CUSTOMS_SURCHARGES';

    const DUTY = 'DUTY';

    const EXCISE_TAX = 'EXCISE_TAX';

    const FOREIGN_EXCHANGE_TAX = 'FOREIGN_EXCHANGE_TAX';

    const GENERAL_SALES_TAX = 'GENERAL_SALES_TAX';

    const IMPORT_LICENSE_FEE = 'IMPORT_LICENSE_FEE';

    const INTERNAL_ADDITIONAL_TAXES = 'INTERNAL_ADDITIONAL_TAXES';

    const INTERNAL_SENSITIVE_PRODUCTS_TAX = 'INTERNAL_SENSITIVE_PRODUCTS_TAX';

    const OTHER = 'OTHER';

    const SENSITIVE_PRODUCTS_TAX = 'SENSITIVE_PRODUCTS_TAX';

    const STAMP_TAX = 'STAMP_TAX';

    const STATISTICAL_TAX = 'STATISTICAL_TAX';

    const TRANSPORT_FACILITIES_TAX = 'TRANSPORT_FACILITIES_TAX';


}

