<?php

namespace MobileCart\FedexBundle\Api\RateV10\SimpleType;

/**
 *
 *
 */
class RequestedShippingDocumentType extends SimpleTypeAbstract
{
    const CERTIFICATE_OF_ORIGIN = 'CERTIFICATE_OF_ORIGIN';

    const COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE';

    const CUSTOMER_SPECIFIED_LABELS = 'CUSTOMER_SPECIFIED_LABELS';

    const GENERAL_AGENCY_AGREEMENT = 'GENERAL_AGENCY_AGREEMENT';

    const LABEL = 'LABEL';

    const NAFTA_CERTIFICATE_OF_ORIGIN = 'NAFTA_CERTIFICATE_OF_ORIGIN';

    const PRO_FORMA_INVOICE = 'PRO_FORMA_INVOICE';

    const RETURN_INSTRUCTIONS = 'RETURN_INSTRUCTIONS';


}

