<?php

namespace MobileCart\FedexBundle\Api\RateV10\SimpleType;

/**
 * Identifies the collection of special service offered by FedEx. 
 *
 *
 */
class ShipmentSpecialServiceType extends SimpleTypeAbstract
{
    const BROKER_SELECT_OPTION = 'BROKER_SELECT_OPTION';

    const CALL_BEFORE_DELIVERY = 'CALL_BEFORE_DELIVERY';

    const COD = 'COD';

    const CUSTOM_DELIVERY_WINDOW = 'CUSTOM_DELIVERY_WINDOW';

    const DANGEROUS_GOODS = 'DANGEROUS_GOODS';

    const DO_NOT_BREAK_DOWN_PALLETS = 'DO_NOT_BREAK_DOWN_PALLETS';

    const DO_NOT_STACK_PALLETS = 'DO_NOT_STACK_PALLETS';

    const DRY_ICE = 'DRY_ICE';

    const EAST_COAST_SPECIAL = 'EAST_COAST_SPECIAL';

    const ELECTRONIC_TRADE_DOCUMENTS = 'ELECTRONIC_TRADE_DOCUMENTS';

    const EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION';

    const EXTREME_LENGTH = 'EXTREME_LENGTH';

    const FOOD = 'FOOD';

    const FREIGHT_GUARANTEE = 'FREIGHT_GUARANTEE';

    const FUTURE_DAY_SHIPMENT = 'FUTURE_DAY_SHIPMENT';

    const HOLD_AT_LOCATION = 'HOLD_AT_LOCATION';

    const HOME_DELIVERY_PREMIUM = 'HOME_DELIVERY_PREMIUM';

    const INSIDE_DELIVERY = 'INSIDE_DELIVERY';

    const INSIDE_PICKUP = 'INSIDE_PICKUP';

    const LIFTGATE_DELIVERY = 'LIFTGATE_DELIVERY';

    const LIFTGATE_PICKUP = 'LIFTGATE_PICKUP';

    const LIMITED_ACCESS_DELIVERY = 'LIMITED_ACCESS_DELIVERY';

    const LIMITED_ACCESS_PICKUP = 'LIMITED_ACCESS_PICKUP';

    const PENDING_SHIPMENT = 'PENDING_SHIPMENT';

    const POISON = 'POISON';

    const PROTECTION_FROM_FREEZING = 'PROTECTION_FROM_FREEZING';

    const RETURN_SHIPMENT = 'RETURN_SHIPMENT';

    const SATURDAY_DELIVERY = 'SATURDAY_DELIVERY';

    const SATURDAY_PICKUP = 'SATURDAY_PICKUP';

    const TOP_LOAD = 'TOP_LOAD';


}

