<?php

namespace MobileCart\FedexBundle\Api\RateV10\SimpleType;

/**
 *
 *
 */
class SurchargeType extends SimpleTypeAbstract
{
    const ADDITIONAL_HANDLING = 'ADDITIONAL_HANDLING';

    const ANCILLARY_FEE = 'ANCILLARY_FEE';

    const APPOINTMENT_DELIVERY = 'APPOINTMENT_DELIVERY';

    const BROKER_SELECT_OPTION = 'BROKER_SELECT_OPTION';

    const CANADIAN_DESTINATION = 'CANADIAN_DESTINATION';

    const CLEARANCE_ENTRY_FEE = 'CLEARANCE_ENTRY_FEE';

    const COD = 'COD';

    const CUT_FLOWERS = 'CUT_FLOWERS';

    const DANGEROUS_GOODS = 'DANGEROUS_GOODS';

    const DELIVERY_AREA = 'DELIVERY_AREA';

    const DELIVERY_CONFIRMATION = 'DELIVERY_CONFIRMATION';

    const DOCUMENTATION_FEE = 'DOCUMENTATION_FEE';

    const DRY_ICE = 'DRY_ICE';

    const EMAIL_LABEL = 'EMAIL_LABEL';

    const EUROPE_FIRST = 'EUROPE_FIRST';

    const EXCESS_VALUE = 'EXCESS_VALUE';

    const EXHIBITION = 'EXHIBITION';

    const EXPORT = 'EXPORT';

    const EXTREME_LENGTH = 'EXTREME_LENGTH';

    const FEDEX_TAG = 'FEDEX_TAG';

    const FICE = 'FICE';

    const FLATBED = 'FLATBED';

    const FREIGHT_GUARANTEE = 'FREIGHT_GUARANTEE';

    const FREIGHT_ON_VALUE = 'FREIGHT_ON_VALUE';

    const FUEL = 'FUEL';

    const HOLD_AT_LOCATION = 'HOLD_AT_LOCATION';

    const HOME_DELIVERY_APPOINTMENT = 'HOME_DELIVERY_APPOINTMENT';

    const HOME_DELIVERY_DATE_CERTAIN = 'HOME_DELIVERY_DATE_CERTAIN';

    const HOME_DELIVERY_EVENING = 'HOME_DELIVERY_EVENING';

    const INSIDE_DELIVERY = 'INSIDE_DELIVERY';

    const INSIDE_PICKUP = 'INSIDE_PICKUP';

    const INSURED_VALUE = 'INSURED_VALUE';

    const INTERHAWAII = 'INTERHAWAII';

    const LIFTGATE_DELIVERY = 'LIFTGATE_DELIVERY';

    const LIFTGATE_PICKUP = 'LIFTGATE_PICKUP';

    const LIMITED_ACCESS_DELIVERY = 'LIMITED_ACCESS_DELIVERY';

    const LIMITED_ACCESS_PICKUP = 'LIMITED_ACCESS_PICKUP';

    const METRO_DELIVERY = 'METRO_DELIVERY';

    const METRO_PICKUP = 'METRO_PICKUP';

    const NON_MACHINABLE = 'NON_MACHINABLE';

    const OFFSHORE = 'OFFSHORE';

    const ON_CALL_PICKUP = 'ON_CALL_PICKUP';

    const OTHER = 'OTHER';

    const OUT_OF_DELIVERY_AREA = 'OUT_OF_DELIVERY_AREA';

    const OUT_OF_PICKUP_AREA = 'OUT_OF_PICKUP_AREA';

    const OVERSIZE = 'OVERSIZE';

    const OVER_DIMENSION = 'OVER_DIMENSION';

    const PIECE_COUNT_VERIFICATION = 'PIECE_COUNT_VERIFICATION';

    const PRE_DELIVERY_NOTIFICATION = 'PRE_DELIVERY_NOTIFICATION';

    const PRIORITY_ALERT = 'PRIORITY_ALERT';

    const PROTECTION_FROM_FREEZING = 'PROTECTION_FROM_FREEZING';

    const REGIONAL_MALL_DELIVERY = 'REGIONAL_MALL_DELIVERY';

    const REGIONAL_MALL_PICKUP = 'REGIONAL_MALL_PICKUP';

    const RESIDENTIAL_DELIVERY = 'RESIDENTIAL_DELIVERY';

    const RESIDENTIAL_PICKUP = 'RESIDENTIAL_PICKUP';

    const RETURN_LABEL = 'RETURN_LABEL';

    const SATURDAY_DELIVERY = 'SATURDAY_DELIVERY';

    const SATURDAY_PICKUP = 'SATURDAY_PICKUP';

    const SIGNATURE_OPTION = 'SIGNATURE_OPTION';

    const TARP = 'TARP';

    const THIRD_PARTY_CONSIGNEE = 'THIRD_PARTY_CONSIGNEE';

    const TRANSMART_SERVICE_FEE = 'TRANSMART_SERVICE_FEE';


}

